tinymce.addI18n('de_DE',{
"Cut": "Ausschneiden",
"Heading 5": "Überschrift 5",
"Header 2": "Titel 2",
"Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead.": "Ihr Browser unterstützt keine direkten Zugriff auf die Zwischenablage. Bitte verwenden Sie stattdessen die Strg + X \ / C \ / V Tastenkombinationen.",
"Heading 4": "Überschrift 4",
"Div": "Div",
"Heading 2": "Überschrift 2",
"Paste": "Einfügen",
"Close": "Schließen",
"Font Family": "Schrift",
"Pre": "Pre",
"Align right": "Rechtsbündig",
"New document": "neues Dokument",
"Blockquote": "EinrÜcken",
"Numbered list": "nummerierte Liste",
"Heading 1": "Überschrift 1",
"Headings": "Überschriften",
"Increase indent": "Einzug vergrößern",
"Formats": "Formate",
"Headers": "Überschriften",
"Select all": "Alles auswählen",
"Header 3": "Titel 3",
"Blocks": "Blöcke",
"Undo": "Rückgängig machen",
"Strikethrough": "Durchgestrichen",
"Bullet list": "Auflistung",
"Header 1": "Titel 1",
"Superscript": "Hochgestellt",
"Clear formatting": "Formatierung löschen",
"Font Sizes": "Schriftgrößen",
"Subscript": "Index",
"Header 6": "Titel 6",
"Redo": "wiederholen",
"Paragraph": "Absatz",
"Ok": "Ok",
"Bold": "Fett",
"Code": "Code",
"Italic": "Kursiv",
"Align center": "mittig ausrichten",
"Header 5": "Titel 5",
"Heading 6": "Überschrift 6",
"Heading 3": "Überschrift 3",
"Decrease indent": "Einzug verkleinern",
"Header 4": "Titel 4",
"Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Einfügen ist jetzt im Klartext-Modus. Inhalt wird nun als einfacher Text eingefügt we, bis Sie  Sie diese Option wieder ausschalten.",
"Underline": "Unterstreichen",
"Cancel": "Abbrechen",
"Justify": "Blocksatz",
"Inline": "linear",
"Copy": "Kopieren",
"Align left": "links ausrichten",
"Visual aids": "Visuelle Hilfen",
"Lower Greek": "tiefgestellt",
"Square": "PLatz",
"Default": "Standard",
"Lower Alpha": "Lower Alpha",
"Circle": "Kreis",
"Disc": "Scheibe",
"Upper Alpha": "Großbuchstaben",
"Upper Roman": "hochgestellt",
"Lower Roman": "Lower Roman",
"Name": "Name",
"Anchor": "Anker",
"You have unsaved changes are you sure you want to navigate away?": "Sie haben die Änderungen nicht gespeichert sind Sie sicher, weg wollen?",
"Restore last draft": "Zurück zum letzten Entwurf",
"Special character": "Sonderzeichen",
"Source code": "Source code",
"Color": "Farbe",
"Right to left": "Rechts nach Links",
"Left to right": "Links nach Rechts",
"Emoticons": "Emoticons",
"Robots": "Robots",
"Document properties": "Dokumenteigenschaften",
"Title": "Titel",
"Keywords": "Schlüsselwörter",
"Encoding": "Codierung",
"Description": "Beschreibung",
"Author": "Author",
"Fullscreen": "Vollbild",
"Horizontal line": "Horizontale Linie",
"Horizontal space": "horizontaler Abstand",
"Insert\/edit image": "Einfügen\/Bild bearbeiten",
"General": "Allgemeines",
"Advanced": "Erweiterte",
"Source": "Source",
"Border": "Rand",
"Constrain proportions": "Proportionen",
"Vertical space": "vertikaler Raum",
"Image description": "Bildeigenschaften",
"Style": "Style",
"Dimensions": "Größe",
"Insert image": "Bild einfügen",
"Insert date\/time": "Datum einfügen\/Zeit",
"Remove link": "Link entfernen",
"Url": "Url",
"Text to display": "Text angezeigen",
"Anchors": "Anker",
"Insert link": "Link einfügen",
"New window": "neues Fenster",
"None": "Keine",
"The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?": "Der von Ihnen eingegebene URL scheint ein externer Link sein. Sie müssen den Präfix http verwenden: \/\/ Präfix?",
"Target": "Ziel",
"The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?": "Der von Ihnen eingegebene URL scheint eine E-Mail-Adresse sein. Möchten Sie die erforderlichen mailto hinzufügen?",
"Insert\/edit link": "Einfügen\/\Link bearbeiten",
"Insert\/edit video": "Einfügen\/\Video bearbeiten",
"Poster": "Poster",
"Alternative source": "alternative Quelle",
"Paste your embed code below:": "Fügen Sie Ihren Code ein:",
"Insert video": "Video einfügen",
"Embed": "Einbetten",
"Nonbreaking space": "geschütztes Leerzeichen",
"Page break": "Seitenumbruch",
"Paste as text": "Einfügen als Text",
"Preview": "Vorschau",
"Print": "Drucken",
"Save": "Speichern",
"Could not find the specified string.": "Zeichenfolge konnte nicht gefunden werden.",
"Replace": "Ersetzen",
"Next": "Nächster",
"Whole words": "Ganzes Wort",
"Find and replace": "Suchen und Ersetzen",
"Replace with": "Ersetzen mit",
"Find": "Finden",
"Replace all": "Alles ersetzen",
"Match case": "Groß-",
"Prev": "zurück ",
"Spellcheck": "Rechtschreibprüfung",
"Finish": "Fertig",
"Ignore all": "Alles ignorieren",
"Ignore": "Ignorieren",
"Add to Dictionary": "Zum Wörterbuch",
"Insert row before": "Reihe davor einfügen",
"Rows": "Reihen",
"Height": "Höhe",
"Paste row after": "Reihe danach einfügen",
"Alignment": "Ausrichtung",
"Border color": "Randfarbe",
"Column group": "Spaltengruppe",
"Row": "Reihe",
"Insert column before": "Spalte davor einfügen",
"Split cell": "Zellen teilen",
"Cell padding": "Zellauffüllung",
"Cell spacing": "Zellenabstand",
"Row type": "Zeilentyp",
"Insert table": "Tabelle einfügen",
"Body": "Body",
"Caption": "Bildunterschrift",
"Footer": "Fußzeile",
"Delete row": "Zeile löschen",
"Paste row before": "Reihe davor einfügen",
"Scope": "Umfang",
"Delete table": "Tabelle löschen",
"H Align": "H Bündig",
"Top": "Oben",
"Header cell": "Kopfzelle",
"Column": "Spalte",
"Row group": "Zeilengruppe",
"Cell": "Zelle",
"Middle": "Mitte",
"Cell type": "Zelltyp",
"Copy row": "Kopiere Reihe",
"Row properties": "Zeilen Eigenschaften",
"Table properties": "Tabelle Eigenschaften",
"Bottom": "am Boden",
"V Align": "V Bündig",
"Header": "Kopfzeile",
"Right": "Rechts",
"Insert column after": "Spalte danach einfügen",
"Cols": "Spalten",
"Insert row after": "Spalte danach einfügen",
"Width": "Breite",
"Cell properties": "Zellen eigenschaften",
"Left": "Links",
"Cut row": "Zeile ausschneiden",
"Delete column": "Spalte löschen",
"Center": "Mitte",
"Merge cells": "Zellen verbinden",
"Insert template": "Template einfügen",
"Templates": "Themplates",
"Background color": "Hinterdrundfarbe",
"Custom...": "Benutzerdefinierte...",
"Custom color": "Benutzerdefinierte Farbe",
"No color": "keine Farbe",
"Text color": "Textfarbe",
"Show blocks": "Zeige Blöcke",
"Show invisible characters": "Zeige versteckte Zeichen",
"Words: {0}": "Wörter : {0}",
"Insert": "Einfügen",
"File": "Dateien",
"Edit": "Bearbeiten",
"Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help": "Rich-Text-Area. Drücken Sie ALT-F9 für Menü. Drücken Sie ALT-F10 für die Symbolleiste. Drücken Sie ALT-0 für Hilfe",
"Tools": "Outils",
"View": "Voir",
"Table": "Tableau",
"Format": "Format"
});